//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersGrades
    {
        public int Id { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Grades Grades { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
