//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersGrades
    {
        public int Id { get; set; }
        public int GradeId { get; set; }
        public int TopicId { get; set; }
        public int UserId { get; set; }
    
        public virtual Grades Grades { get; set; }
        public virtual Topics Topics { get; set; }
        public virtual Users Users { get; set; }
    }
}
