//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uchet.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInSubjects
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int SubjectId { get; set; }
    
        public virtual Subjects Subjects { get; set; }
        public virtual Users Users { get; set; }
    }
}
